port 0
unixsocket /var/lib/trade-engine-v2/redis.sock
unixsocketperm 700
daemonize no
dir /var/lib/trade-engine-v2
save ""
appendonly no
maxmemory 128mb
maxmemory-policy noeviction
logfile /var/log/trade-engine-v2/redis.log
